In [1]:
#step -1 
import pandas as pd

In [4]:
#read local csv file 
df =pd.read_csv("customers.csv" )
df

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
...,...,...,...,...,...,...,...,...,...
1005,CUST0996,Vinsen,47.0,Male,Bengkulu,2024-06-09,ibrani64@example.org,8585892932,Yes
1006,CUST0997,Ulya,59.0,Female,Sulawesi Utara,2024-06-23,putri15@example.com,81976792782,Yes
1007,CUST0998,Dina,41.0,Female,DKI Jakarta,2025-01-01,dina912@example.com,85499775196,Yes
1008,CUST0999,Yahya,63.0,Male,Kalimantan Timur,2023-12-12,chartati@example.net,8912787724,No
1009,CUST1000,Olga,25.0,Male,Banten,2025-02-21,olga_89@example.com,899714462,Yes

In [ ]:
#Opening csv file using url 
import requests
from io import StringIO
url ="place url "
headers={}
req=requests.get(url, headers=headers)
data =StringIO(req.text)

pd.read_csv(data)

In [ ]:
#in case future ager  mai columns given na ho to  aur apaka first row column bn gaya ho to then app ye  snipit use kr ke  coulns design kr sakte hai 

# pd.read_csv('file name ', name=['sno', 'movie ','reledate' ,'rating '])

In [6]:
df
#index _col prameter 
newdf=pd.read_csv('customers.csv' ,index_col=['customer_id']) #here Customer Id become your index prameter 

newdf

,name,age,gender,state,signup_date,email,phone_number,subscribe
customer_id,,,,,,,,
CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
...,...,...,...,...,...,...,...,...
CUST0996,Vinsen,47.0,Male,Bengkulu,2024-06-09,ibrani64@example.org,8585892932,Yes
CUST0997,Ulya,59.0,Female,Sulawesi Utara,2024-06-23,putri15@example.com,81976792782,Yes
CUST0998,Dina,41.0,Female,DKI Jakarta,2025-01-01,dina912@example.com,85499775196,Yes
CUST0999,Yahya,63.0,Male,Kalimantan Timur,2023-12-12,chartati@example.net,8912787724,No
CUST1000,Olga,25.0,Male,Banten,2025-02-21,olga_89@example.com,899714462,Yes

In [10]:
#header prameter 
pd.read_csv('customers.csv' ,header=0)

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
...,...,...,...,...,...,...,...,...,...
1005,CUST0996,Vinsen,47.0,Male,Bengkulu,2024-06-09,ibrani64@example.org,8585892932,Yes
1006,CUST0997,Ulya,59.0,Female,Sulawesi Utara,2024-06-23,putri15@example.com,81976792782,Yes
1007,CUST0998,Dina,41.0,Female,DKI Jakarta,2025-01-01,dina912@example.com,85499775196,Yes
1008,CUST0999,Yahya,63.0,Male,Kalimantan Timur,2023-12-12,chartati@example.net,8912787724,No
1009,CUST1000,Olga,25.0,Male,Banten,2025-02-21,olga_89@example.com,899714462,Yes

In [13]:
#use_cols parameter 
#fillter relevent column 
df
pd.read_csv('customers.csv',usecols=['customer_id','name','phone_number'])

     customer_id     name  phone_number
0       CUST0001    Gandi    8422757160
1       CUST0002    Cecep   88171122035
2       CUST0003  Artawan    8692932468
3       CUST0004    Mulya    8515735210
4       CUST0005   Taufik   81034538051
...          ...      ...           ...
1005    CUST0996   Vinsen    8585892932
1006    CUST0997     Ulya   81976792782
1007    CUST0998     Dina   85499775196
1008    CUST0999    Yahya    8912787724
1009    CUST1000     Olga     899714462

[1010 rows x 3 columns]

In [12]:
#nrows 
pd.read_csv('customers.csv' , nrows=11)

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
5,CUST0006,Genta,20.0,Female,Kalimantan Timur,2025-06-04,puyainah@example.com,818757946920,Yes
6,CUST0007,Dimas,18.0,Male,Sumatera Barat,2024-11-14,224dimas@example.com,8189638436,No
7,CUST0008,Nilam,26.0,Female,Jawa Timur,2025-05-22,tariandriani@example.org,8649564474,Yes
8,CUST0009,Emas,29.0,Male,Nusa Tenggara Timur,2023-11-30,emas288@example.com,8712019987,Yes
9,CUST0010,Kani,64.0,Female,Kalimantan Utara,2025-03-05,asmiantosimbolon@example.org,8691418746,Yes
10,CUST0011,Putri,62.0,Female,Kepulauan Riau,2025-01-15,jailanidarsirah@example.org,811765466,Yes

In [ ]:
#encoding Parameter 
#this snipit use for  fixing  UNICODEDECODERORR
# pd.read_csv('customers.csv' , encoding='latin-1')

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
...,...,...,...,...,...,...,...,...,...
1005,CUST0996,Vinsen,47.0,Male,Bengkulu,2024-06-09,ibrani64@example.org,8585892932,Yes
1006,CUST0997,Ulya,59.0,Female,Sulawesi Utara,2024-06-23,putri15@example.com,81976792782,Yes
1007,CUST0998,Dina,41.0,Female,DKI Jakarta,2025-01-01,dina912@example.com,85499775196,Yes
1008,CUST0999,Yahya,63.0,Male,Kalimantan Timur,2023-12-12,chartati@example.net,8912787724,No
1009,CUST1000,Olga,25.0,Male,Banten,2025-02-21,olga_89@example.com,899714462,Yes

In [ ]:
#skip bad lines 
#Pandas will ignore and skip any corrupted or malformed rows
pd.read_csv('customers.csv',sep=',' ,encoding='latin-1',on_bad_lines='skip')

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes
...,...,...,...,...,...,...,...,...,...
1005,CUST0996,Vinsen,47.0,Male,Bengkulu,2024-06-09,ibrani64@example.org,8585892932,Yes
1006,CUST0997,Ulya,59.0,Female,Sulawesi Utara,2024-06-23,putri15@example.com,81976792782,Yes
1007,CUST0998,Dina,41.0,Female,DKI Jakarta,2025-01-01,dina912@example.com,85499775196,Yes
1008,CUST0999,Yahya,63.0,Male,Kalimantan Timur,2023-12-12,chartati@example.net,8912787724,No
1009,CUST1000,Olga,25.0,Male,Banten,2025-02-21,olga_89@example.com,899714462,Yes

In [14]:
#handling dates
pd.read_csv('Match_Info.csv',parse_dates=['match_date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_number     1243 non-null   int64
 1   team1            1243 non-null   str
 2   team2            1243 non-null   str
 3   match_date       1243 non-null   datetime64[us]
 4   toss_winner      1243 non-null   str
 5   toss_decision    1243 non-null   str
 6   result           1243 non-null   str
 7   eliminator       16 non-null     str
 8   winner           1218 non-null   str
 9   player_of_match  1243 non-null   str
 10  venue            1243 non-null   str
 11  city             1192 non-null   str
 12  team1_players    1243 non-null   str
 13  team2_players    1243 non-null   str
dtypes: datetime64[us](1), int64(1), str(12)
memory usage: 136.1 KB

In [32]:
#Converters 
def rename(name):
    if name=='Royal Challengers Bangalore':
        return 'RCB'
    elif name=='Kolkata Knight Riders':
        return 'KKR'
    else:
        return name
pd.read_csv('Match_Info.csv' , converters={'team1':rename, 'team2':rename , 'toss_winner':rename})

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players
0,501208,Deccan Chargers,RCB,2011-04-14,RCB,field,Win,NaN,Deccan Chargers,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,"S Sohal, S Dhawan, KC Sangakkara, B Chipli, JP...","MA Agarwal, TM Dilshan, Z Khan, V Kohli, AB de..."
1,1216505,RCB,Delhi Capitals,2020-11-02,Delhi Capitals,field,Win,NaN,Delhi Capitals,A Nortje,Sheikh Zayed Stadium,Abu Dhabi,"JR Philippe, D Padikkal, V Kohli, AB de Villie...","PP Shaw, S Dhawan, AM Rahane, SS Iyer, RR Pant..."
2,1359481,Delhi Capitals,Gujarat Titans,2023-04-04,Gujarat Titans,field,Win,NaN,Gujarat Titans,B Sai Sudharsan,"Arun Jaitley Stadium, Delhi",Delhi,"KK Ahmed, DA Warner, PP Shaw, MR Marsh, SN Kha...","J Little, WP Saha, Shubman Gill, B Sai Sudhars..."
3,1178398,KKR,Chennai Super Kings,2019-04-09,Chennai Super Kings,field,Win,NaN,Chennai Super Kings,DL Chahar,MA Chidambaram Stadium,Chennai,"CA Lynn, SP Narine, RV Uthappa, N Rana, KD Kar...","SR Watson, F du Plessis, SK Raina, AT Rayudu, ..."
4,1529313,Delhi Capitals,KKR,2026-05-24,KKR,field,Win,NaN,Delhi Capitals,Kuldeep Yadav,"Eden Gardens, Kolkata",Kolkata,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,548354,Kings XI Punjab,Rajasthan Royals,2012-05-05,Rajasthan Royals,bat,Win,NaN,Rajasthan Royals,SR Watson,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"SE Marsh, Mandeep Singh, N Saini, DJ Hussey, A...","R Dravid, AM Rahane, SR Watson, AL Menaria, BJ..."
1239,829705,KKR,Mumbai Indians,2015-04-08,KKR,field,Win,NaN,Kolkata Knight Riders,M Morkel,Eden Gardens,Kolkata,"RV Uthappa, G Gambhir, MK Pandey, SA Yadav, YK...","RG Sharma, AJ Finch, AP Tare, AT Rayudu, CJ An..."
1240,392236,RCB,Deccan Chargers,2009-05-21,RCB,bat,Win,NaN,Royal Challengers Bangalore,MK Pandey,SuperSport Park,Centurion,"JH Kallis, MK Pandey, RE van der Merwe, R Drav...","AC Gilchrist, HH Gibbs, TL Suman, A Symonds, R..."
1241,598052,Kings XI Punjab,Rajasthan Royals,2013-05-09,Rajasthan Royals,field,Win,NaN,Rajasthan Royals,KK Cooper,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"Mandeep Singh, AC Gilchrist, SE Marsh, DJ Huss...","R Dravid, AM Rahane, SR Watson, SV Samson, BJ ..."
1242,1359499,Mumbai Indians,Sunrisers Hyderabad,2023-04-18,Sunrisers Hyderabad,field,Win,NaN,Mumbai Indians,C Green,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,"RP Meredith, RG Sharma, Ishan Kishan, C Green,...","T Natarajan, HC Brook, MA Agarwal, RA Tripathi..."

In [22]:
#NaN values 
#  Python which specific words or symbols in your file should be treated as "Missing Data" (Empty Cells).
pd.read_csv('customers.csv').head(2)

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No

In [ ]:
#loding huge data sets 
dfs=pd.read_csv('customers.csv', chunksize=100)