In [79]:
import pandas as pd

In [80]:
myData={
    'name':['ayan','faiz','zubair','muslim'],
    'age':[21,19,20,22],
    'salary':[21000,24000,27000,50000]

}

df=pd.DataFrame(myData)
type(df)

pandas.DataFrame

In [177]:
order=pd.read_csv('orders.csv')
order.sample(2)
order.head(10)
order.tail(10)
order.shape

(50, 11)

In [82]:
order.dtypes
order.info()
order.describe()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     str
 1   order_date   50 non-null     str
 2   ship_date    50 non-null     str
 3   ship_mode    50 non-null     str
 4   customer_id  50 non-null     str
 5   region       50 non-null     str
 6   product_id   50 non-null     str
 7   category     50 non-null     str
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), str(8)
memory usage: 4.4 KB

             sales   quantity       profit
count    50.000000  50.000000    50.000000
mean    300.792000   3.920000   -20.550000
std     547.564035   1.977836   251.767027
min       2.500000   2.000000 -1665.100000
25%      20.075000   2.000000     2.500000
50%      74.650000   3.000000     8.350000
75%     249.875000   5.000000    17.650000
max    3083.400000   9.000000   240.300000

In [83]:
order.columns=[['order_id', 'order_date', 'ship_date', 'ship_mode', 'customerkey',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
     ]
order.sample(3)

pd.read_csv('orders.csv',header=1).sample(3)
order.head()

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [84]:
# Data Selection 
order.sample()
#data frame with one columns called Series 
series = order['order_id']
series.head()

new_df=order[['order_id','region','sales']]
new_df.sample(3)

          order_id   region sales
43  CA-2021-139619    South  95.6
44  CA-2020-118255  Central  46.0
18  CA-2018-143336     West   8.6

In [85]:
#Filtering  row with indexLocation (iloc)
#iloc always take numeric index  for rows and columns 
order[0:5]
order[:11]
order[22:30:2] #[start: end: steps ]
order.iloc[[5,7,9,2,10,15,17,30]]
order.iloc[[3,6,9],[0,5,9]] # iloc[[rows _ index ], [Columns _ index ]]

order.sample()

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [86]:
#loc -> do not required integer index 
# also used for  selcting rows and columns 
#required columns values 

order.loc[0:10]
order.loc[[2,3,4,5,7],['order_id','sales']]

new_df=order.set_index('customerkey')

In [87]:
#Sorting , Conditional data  filtiring
order.sort_index(ascending=False)
# order.sort_values()
order.reset_index(drop=True, inplace=True ) # drop=True , means droping existing index columns 

order.head(2)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [88]:
#Data filteration 
order.columns=order.columns.get_level_values(0) #multilevel error fix karne ke liye use kr sakte hai 
fc=order['region']=='South'
order.loc[fc]
order.loc[fc]
order.loc[(order['region']=='West')& (order['profit']>100) & (order['category']=='Furniture')]
new_df=order.set_index('order_id')
new_df.loc[['US-2019-108966'],['category','sales']]

                       category  sales
order_id
US-2019-108966        Furniture  957.6
US-2019-108966  Office Supplies   22.4

In [89]:
#check multilevel columns 
multilevel= isinstance(order.columns, pd.MultiIndex)
multilevel

False

In [90]:
order.loc[(order['profit']>50)|(order['sales']>100)].sample(2)
#without loc 
order[order['category']=='Office Supplies'][order['profit']>100]

C:\Users\hp\AppData\Local\Temp\ipykernel_6460\300838425.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  order[order['category']=='Office Supplies'][order['profit']>100]

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6

how to  create  and update and delete the columns

In [91]:
#create columns 
order['Country']='India'
order.head(2)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit,Country
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,India
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,India

In [92]:
#update columns 
order['Country']='China'
order.head(2)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit,Country
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,China
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,China

In [93]:
order.drop(columns='Country').head(2)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [94]:
#
order['profit_flag']=1
order.loc[order['profit']<=0,'profit_flag']=0

order.sample(5)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit,Country,profit_flag
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,China,1
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,China,1
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,China,1
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,China,1
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,China,0

In [95]:
#profit status 
order['profit_status']='loss'
order.loc[order['profit']<=0,'profit_status']='loss'
order.loc[order['profit']<=50,'profit_status']='less Profit'
order.loc[order['profit']>50,'profit_status']='good profit'

order.sample(3)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit,Country,profit_flag,profit_status
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,China,1,less Profit
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,China,1,less Profit
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,China,1,less Profit

In [96]:
#String function 
name='ayan'
name.upper()
name.capitalize()
name.startswith('a') #True 
name.endswith('n') #True 

#applying str function on order dataset 
order.sample(2)
order['category_upper']=order['category'].str.upper()
order
#droping columns 
order.drop(columns='category_upper', inplace=True)
order.sample(2)

,order_id,order_date,ship_date,ship_mode,customerkey,region,product_id,category,sales,quantity,profit,Country,profit_flag,profit_status
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,China,1,less Profit
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,China,1,less Profit

In [113]:
#dealing with null Values and  droping dublicates Values 
customer=pd.read_csv('customers.csv')


# #check na_value 
customer.isnull().sum()
# #droping null values 

customer.dropna(subset='age', inplace=True )

customer.info()

<class 'pandas.DataFrame'>
Index: 954 entries, 0 to 1009
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   954 non-null    str
 1   name          954 non-null    str
 2   age           954 non-null    float64
 3   gender        954 non-null    str
 4   state         904 non-null    str
 5   signup_date   954 non-null    str
 6   email         954 non-null    str
 7   phone_number  954 non-null    int64
 8   subscribe     954 non-null    str
dtypes: float64(1), int64(1), str(7)
memory usage: 74.5 KB

In [123]:
#filling null Values  |Specific Columns 
customer.isnull().sum()
customer['state']=customer['state'].fillna('unknown')
# customer.fillna({'state': 'Unknown'}, inplace=True)

customer.isnull().sum()

customer_id     0
name            0
age             0
gender          0
state           0
signup_date     0
email           0
phone_number    0
subscribe       0
dtype: int64

In [147]:
#droping dublicates 
customer[customer.duplicated()] 

customer.drop_duplicates(keep='last',inplace=True)
customer.duplicated().sum()

np.int64(0)

In [178]:
# Working with Date and time in pandas 
from datetime import date, time,datetime
order.sample(3)
order.dtypes
order['order_date']=pd.to_datetime(order['order_date'],format='%d-%m-%Y')
order['ship_date']=pd.to_datetime(order['ship_date'],format='%d-%m-%Y')
order.order_date[order.order_date.dt.day] #use .dt

8    2018-06-09
8    2018-06-09
12   2021-04-15
11   2018-06-09
11   2018-06-09
9    2018-06-09
9    2018-06-09
9    2018-06-09
9    2018-06-09
9    2018-06-09
9    2018-06-09
9    2018-06-09
15   2019-11-22
5    2018-06-09
22   2020-12-09
22   2020-12-09
11   2018-06-09
13   2020-12-05
27   2019-09-17
27   2019-09-17
27   2019-09-17
9    2018-06-09
9    2018-06-09
16   2018-11-11
25   2020-01-16
16   2018-11-11
16   2018-11-11
17   2018-05-13
17   2018-05-13
17   2018-05-13
17   2018-05-13
17   2018-05-13
17   2018-05-13
17   2018-05-13
19   2018-08-27
8    2018-06-09
8    2018-06-09
27   2019-09-17
27   2019-09-17
27   2019-09-17
27   2019-09-17
10   2018-06-09
17   2018-05-13
19   2018-08-27
11   2018-06-09
11   2018-06-09
20   2018-08-27
20   2018-08-27
20   2018-08-27
18   2018-08-27
Name: order_date, dtype: datetime64[us]

In [189]:
order.dtypes
order['order_date'].dt.year
order['order_date'].dt.day
order['order_date'].dt.month

0     11
1     11
2      6
3     10
4     10
5      6
6      6
7      6
8      6
9      6
10     6
11     6
12     4
13    12
14    11
15    11
16    11
17     5
18     8
19     8
20     8
21    12
22    12
23     7
24     9
25     1
26     1
27     9
28     9
29     9
30     9
31     9
32     9
33     9
34    10
35    12
36    12
37    12
38    12
39    12
40    12
41     9
42     7
43     9
44     3
45     3
46    10
47     6
48     6
49     4
Name: order_date, dtype: int32

In [191]:
#difference between two dates 
order['trasative_days']=(order['ship_date']-order['order_date']).dt.days
order.sample(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,trasative_days
11,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,5
38,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,4
37,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,4
21,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,4
36,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,2